In [ ]:
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
#importint the dataset
dataset = pd.read_csv("wine_dataset.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[4.2000e-01 9.9848e-01 5.7000e+01 ... 2.0100e+02 1.5400e+01 4.3000e-02]
 [5.3000e-01 9.9489e-01 2.9000e+01 ... 4.4000e+01 2.0000e+00 6.3000e-02]
 [2.7000e-01 9.9790e-01 5.0000e+01 ... 1.6300e+02 1.3300e+01 7.6000e-02]
 ...
 [4.0000e-01 9.9650e-01 2.4000e+01 ... 5.8000e+01 1.6000e+00 7.9000e-02]
 [6.4000e-01 9.9496e-01 9.0000e+00 ... 1.7000e+01 1.9000e+00 6.6000e-02]
 [1.8000e-01 9.9080e-01 4.2000e+01 ... 1.6700e+02 1.2000e+00 4.1000e-02]]


In [ ]:
print(y)

['White' 'Red' 'White' ... 'Red' 'Red' 'White']


In [ ]:
#label encoding of dependent variable
from sklearn.preprocessing import LabelEncoder
ls = LabelEncoder()
y = ls.fit_transform(y)

In [ ]:
#splitting the dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25, random_state =0)

In [ ]:
print(X_train)

[[1.8000e-01 9.9383e-01 4.5000e+01 ... 1.4700e+02 5.6000e+00 4.7000e-02]
 [3.0500e-01 9.9824e-01 2.6000e+01 ... 1.4100e+02 1.6000e+01 6.1000e-02]
 [3.5000e-01 9.9230e-01 2.1000e+01 ... 1.4400e+02 1.9000e+00 4.0000e-02]
 ...
 [3.0500e-01 9.9331e-01 7.0000e+00 ... 1.1000e+01 1.2000e+00 5.9000e-02]
 [2.3000e-01 9.9520e-01 4.9000e+01 ... 1.6500e+02 2.7000e+00 4.8000e-02]
 [3.4000e-01 9.9556e-01 1.1000e+01 ... 1.1900e+02 1.4000e+00 4.5000e-02]]


In [ ]:
print(X_test)

[[2.1000e-01 9.9215e-01 4.0000e+01 ... 1.4200e+02 3.8000e+00 2.1000e-02]
 [2.6000e-01 9.9490e-01 2.0000e+01 ... 3.8000e+01 1.7000e+00 5.9000e-02]
 [6.9000e-01 9.9610e-01 1.8000e+01 ... 9.4000e+01 1.9000e+00 8.4000e-02]
 ...
 [2.5000e-01 9.9386e-01 4.0000e+00 ... 1.0000e+01 2.0000e+00 4.1000e-02]
 [4.9000e-01 9.9720e-01 2.0000e+01 ... 1.3600e+02 1.9000e+00 1.1000e-01]
 [2.8000e-01 9.9544e-01 5.1000e+01 ... 1.4900e+02 1.1900e+01 5.2000e-02]]


In [ ]:
print(y_train)

[1 1 1 ... 0 1 1]


In [ ]:
print(y_test)

[1 0 0 ... 0 0 1]


In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#training logistic regression model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [ ]:
#Confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 416    4]
 [   5 1200]]


0.9944615384615385

In [ ]:
# visualisation of training set
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(['#FA8072', '#1E90FF']))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(['#FA8072', '#1E90FF'])(i), label = j)
plt.title('Logistic Regression (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()


ValueError: X has 2 features, but StandardScaler is expecting 12 features as input.